export enum ColumnTypes {
  STRING = 'STRING',
  COUNTRY = 'COUNTRY',
  REPRESENTATIVE = 'REPRESENTATIVE',
  CURRENCY = 'CURRENCY',
  DATE = 'DATE',
  TAGS = 'TAGS',
  PROGRESS = 'PROGRESS',
  STAR = 'STAR',
}
